COSC381-2024Fall/Todo-List-CLI

- README.md
- todo.py
In this PR, I added a function `add_task_date` which gives users an option to add a date to a specific task. In this way, I don't need to change the "add_task" function.
The user can now add a due date to a task after the task is created. The due date can also be updated using the same function.
Detailed code changes:
1. Under Todo.py:
- Add a function: add_task_date, this is the function that updates/adds due date
- Updated the print_menu function to reflect the new option
- Updated the main function to make sure the user can use all options correctly
2. In README.md, line 20, python->python3. This is a small fix.
3. In README.md, under Usage, updated the usage to reflect the add/update due date option.
This PR addresses issue #1.
> Add due dates to tasks

- todo.py
This feature enables users to delete several tasks simultaneously by specifying multiple task numbers in one command. Instead of deleting one task at a time, users can enter a comma-separated list (e.g., 2, 4, 5) or a range of tasks (e.g., 2-5), improving efficiency when managing larger to-do lists. This reduces the number of interactions needed, making task management faster and more convenient.
> Allow multiple tasks to be deleted at the same time

- todo.py
- I added to the print statement that occurs once the user creates a task
- The print statement now also prints the task number of the created task
- issue #10 
closes #10
> Added task number to initial print after creating a task

- todo.py
Added the ability to add the estimated completion time for a task.
> changed the todo.py to add a time estamate for task

- TodoList.py
- todo.py
- The Driver code is still in `todo.py`, but the TodoList Class definition is separated in another file `TodoList.py`
- Changed how we deal with `try..except` in `todo.py` by wrapping it around the entire `if..else` statements
> re-factor: modularized overall committed

- todo.py
-Added add_tag function to TodoList class
-   add_tag takes in a task number and prompts the
user to enter a tag for the task
-   it makes checks to see if the given task has a
date already if not, it will fill in the date
with "Date not Assigned" so we can maintain
the list structure used in the date adding
function
issue #13
> Feature: Tasks can be assigned relative tags

- todo.py
- added a delete_all_tasks function that will reset the task list to empty and display a message to the user when complete.
- updated the main menu printed statments to reflected the new option.
- added the elif statement for the delete all option and adjusted the exit option.
issue #25
> Fix: added a delete_all_tasks function

- todo.py
Added code to the add_task def to take a due_date variable, and then create the task with the due date.
issue #15
> Now asks for a due date when initially creating a task.

- todo.py
Made 5. in the menu "update description" and added update_task function which replaces the description of a task with given user number with keyboard input. Quit is now 6.
> Added update_task function to change task description

- todo.py
This update changes the format of the output string from add_task_date function.
> Updating add_task_date

- todo.py
Added a new method task_exists to check if the task has been added before or not as well as changed add_task method to call task_exists before adding the new task.
> Prevent duplicate tasks

- todo.py
Extra indentation within the main function led to a fatal error. This error caused the program to be non-functional. 
This fix allows the program to run as intended 
Resolves: #48
> fix: fatal indentation error

- todo.py
This PR adds a date argument to the `add_task` function in order to prevent a fatal error from occurring. Adding tasks is now functional.
Resolves: #50
> fixed: add task feature with date argument

- todo.py
feature: enable printing of tasks in alphabetical order
1. Added a new main menu option that prints all the tasks in the list in alphabetical order
2. The list_tasks method is now differentiated into to the legacy list_tasks_numeric and the newly implemented list_tasks_alphabetic. The comments describing the functionality of the methods are also updated accordingly.
3. The main menu option numbering is updated. list_tasks_numeric is option 2. list_tasks_alphabetic is option 3. and the rest are bumped down ending at option 6.
issue #5
> add task sorting

- todo.py
To implement the function remove_due_date that removes the due date from a task, I follow a similar structure to  add_task_date method. Check if the task is stored as a tuple (task name and due date), and if so, convert it back to just the task name (a string).
> 14 add remove due date function

- todo.py
Added my menu helper functions
> Commited changes for myrefractor_menubranch

- todo.py
Added comments for my menu issues
> Added comments into peer's issue

- test_get_user_choice.py
- todo.py
- 4 instances were taken into consideration: within range, out of range, wrong type, empty input
- Part of todo.py was changed to match with this implementation (the program still works)
issue #73
> testing: added test for get_user_choice() method

- .github/workflows/test.yml
- test_print_menu.py
issue #80
This pull request is created to check if the workflow is triggered on the creation of the pull request. The following snapshot shows that the workflow was successfully triggered.
The following snapshot shows that the workflow was successfully triggered when new commits were pushed to this branch.
The following snapshot shows that the workflow was successfully triggered when the pull request was re-opened after closing.
> Add GitHub Action for Automated Test Suite on Pull Requests

- todo.py
Makes automatic tests not fail
> changed bitwise or to logical or in get_user_choice

- test_task_exists.py
test_task_exists_found: Checks if task_exists correctly identifies an existing task and returns its index.
test_task_exists_not_found: Ensures that task_exists returns None if the task doesn't exist.
test_task_exists_case_insensitivity: Verifies that task_exists ignores case differences.
test_task_exists_whitespace_handling: Checks that task_exists handles extra whitespace around the task name.
test_task_exists_empty_list: Tests task_exists on an empty list, expecting None.
test_task_exists_empty_string: Confirms that searching for an empty string returns None.
test_task_exists_task_with_only_whitespace: Ensures None is returned when searching for a task name with only whitespace.
test_task_exists_multiple_same_name_tasks: Verifies that if there are duplicate task names, the index of the …
> Testing: test_task_exists.py

- test_delete_all_tasks.py
I have added a testing file for the method of delete_all_tasks
the main things I tested for:
- empty lists, one to multiple task lists up to large inputs
- combinations of adding/deleting tasks in lists
- adding empty tasks and normal string tasks
- repeatedly trying to delete all tasks for all cases
> added testing file for edge cases for large inputs

- test_get_total_tasks.py
This python file tests different list sizes and tests if the lists have the desired test number.
> the test for get_total_tasks method

- test_remove_due_date.py
created test to check for proper deletion and check for empty/deleted list
> Method 16 test

- test_list_tasks.py
Empty Lists
Lists with Tasks
Lists with 1000 Tasks
> Added testing in List_Tasks for

- test_list_tasks_alphabetic.py
Tested:
Passing tests:
Alphabatising a alphabetically sorted list
Alphabatising a not alphabetically sorted list
Alphabatising tasks in upper and lower cases pre sorted alphabetically
Alphabatising tasks in upper and lower cases not sorted alphabetically
Alphabatising tasks with numbers at the start of tasks
Failed tests:
Alphabatising tasks that contain non english characters
> Added test_list_tasks_alphabetic.py

- TodoList.py
- test_add_task_delegate.py
Added to test_add_task_delegate.py five fixtures and tests.
Added tests include:
test_add_task_delegate_valid: if delegate is a valid delegate
test_add_task_delegate_empty_todo: if delegate is added to an empty todo list
test_add_task_delegate_invalid_task_number: if the delegate is added to a valid task number
est_add_task_delegate_invalid_delegate_name: if delegate name has special characters
test_add_task_delegate_blank_delegate_name: if delegate is left blank after selecting to add a delegatetest_add_task_delegate_multiple_del: if more than one delegate is assigned to a task
test_add_task_delegate_large_number_of_tasks: if adding a delegate to a large number of tasks
> Add test for add_task_delegate method. Fixed erros on TodoList.py

- test_main.py
Added some tests to ensure proper exception handling within the main. Specifically checks exceptions when an improper menu option is entered, as well as user error when attempting to create a task.
> Testing main

- test_get_total_tasks2.py
Added tests for the get_total_tasks() function
test_empty_tasks() : tests when the tasks list is empty
test_one() : tests with one task in list
test_large() : creates a large set of tasks and tests
test_deletion() : creates 3 tasks, deletes 1 task
test_all_deletion() : creates a large set of tasks and deletes all of them
> Added testing file for get_total_tasks()

- test_delete_task.py
- test_delete_task2.py
Created test to validate the functionality of deleting a singular task.
> Add Tests for Delete_Task

- test_delete_all_tasks.py
the unit tests for this method were already written, I tested that they all passed and added a new one
> tested delete all test
